CREATE TABLE IF NOT EXISTS nudges(
    ID INT NOT NULL AUTO_INCREMENT,
    question text,
    PRIMARY KEY (ID)
);

INSERT INTO nudges (ID, question)
VALUES (1, 'My idea of a perfect first date is...'),
       (2, 'When it comes to hobbies, I''m really passionate about...'),
       (3, 'I''m always up for an adventure, especially if it involves...'),
       (4, 'Trying new foods and exploring different restaurants is something I love, especially when it comes to...'),
       (5, 'Music is a big part of my life, and I''m particularly into...'),
       (6, 'If I could travel anywhere in the world, I would go to... because...'),
       (7, 'Nature has a special place in my heart, and I would love to spend a romantic weekend...'),
       (8, 'Whether it''s early morning or late at night, you''ll find me...'),
       (9, 'Movie nights are a must for me, and I''m drawn to...'),
       (10, 'A date idea that I find intriguing and would love to try is...'),
       (11, 'When it comes to humor, I appreciate...'),
       (12, 'Family is important to me, and I value...'),
       (13, 'Exploring art and creativity is something I enjoy, especially when it involves...'),
       (14, 'Fitness and staying active are a big part of my life, and I enjoy...'),
       (15, 'I''m a big fan of books, and my favorite genre is...'),
       (16, 'Cooking and trying out new recipes is something I enjoy, especially when it comes to...'),
       (17, 'A perfect weekend for me involves...'),
       (18, 'I find intelligence and intellectual conversations...'),
       (19, 'I''m a pet lover, and I have a soft spot for...'),
       (20, 'Dancing is something I love, especially when it comes to...'),
       (21, 'I enjoy attending live events such as concerts or sports games, especially when it involves...'),
       (22, 'When it comes to fashion, I''m drawn to...'),
       (23, 'I have a passion for volunteering and giving back to the community, particularly when it involves...'),
       (24, 'I''m a big fan of outdoor activities, especially...'),
       (25, 'I enjoy learning new things, and currently, I''m interested in...'),
       (26, 'I''m a traveler at heart, and my favorite type of destination is...'),
       (27, 'Health and wellness are important to me, and I practice...'),
       (28, 'I find a sense of adventure in trying out new cuisines, particularly...'),
       (29, 'I enjoy expressing my creativity through...'),
       (30, 'I''m a fan of board games and game nights, especially when playing...'),
       (31, 'When it comes to politics and current events, I''m interested in...'),
       (32, 'I appreciate small gestures of kindness, such as...'),
       (33, 'I''m a fan of documentaries, especially those that focus on...'),
       (34, 'I enjoy exploring new coffee shops and cafes, particularly when it comes to...'),
       (35, 'I find relaxation in activities such as...'),
       (36, 'I value honesty and open communication, especially when it comes to...'),
       (37, 'I''m a fan of road trips, and my favorite route is...'),
       (38, 'I''m a night owl, and some of my favorite late-night activities are...'),
       (39, 'I enjoy attending cultural events, such as...'),
       (40, 'I have a love for languages, and I''m currently learning...'),
       (41, 'I appreciate a partner who has a passion for...'),
       (42, 'I''m a fan of puzzles and brain teasers, especially when they involve...'),
       (43, 'I find inspiration in nature, particularly when it comes to...'),
       (44, 'I enjoy exploring local markets and discovering unique finds, especially...'),
       (45, 'I''m a fan of spontaneous adventures, particularly when they involve...'),
       (46, 'I appreciate someone with a great sense of humor, especially when it comes to...'),
       (47, 'I enjoy attending live theater performances, particularly those that feature...'),
       (48, 'I find solace in activities such as...'),
       (49, 'I''m a fan of astrology, and my zodiac sign is...'),
       (50, 'I appreciate someone who values personal growth and self-improvement, particularly when it comes to...'),
       (51, 'I enjoy attending art exhibitions, particularly those that showcase...'),
       (52, 'I''m a fan of podcasts, especially those that cover topics like...'),
       (53, 'I find joy in outdoor picnics, especially when they involve...'),
       (54, 'I appreciate a partner who is skilled in...'),
       (55, 'I enjoy attending music festivals, particularly those that feature...'),
       (56, 'I find inspiration in motivational books, particularly those that focus on...'),
       (57, 'I''m a fan of photography, and my favorite subjects to capture are...'),
       (58, 'I enjoy exploring historical sites and landmarks, particularly those that...'),
       (59, 'I appreciate someone who is passionate about environmental causes, especially...'),
       (60, 'I''m a fan of yoga and meditation, particularly when it comes to...'),
       (61, 'I find relaxation in activities such as painting or drawing, especially...'),
       (62, 'I enjoy attending comedy shows, particularly those featuring...'),
       (63, 'I appreciate a partner who has a love for adventure sports, especially...'),
       (64, 'I''m a fan of science fiction, particularly books or movies that explore...'),
       (65, 'I find peace in activities such as gardening or tending to plants, especially...'),
       (66, 'I enjoy attending wine tastings, particularly when it comes to...'),
       (67, 'I appreciate someone who values mindfulness and practices techniques like...'),
       (68, 'I''m a fan of documentaries, especially those that shed light on...'),
       (69, 'I find joy in attending cultural festivals, particularly those that celebrate...'),
       (70, 'I enjoy exploring flea markets and thrift stores, especially when looking for...'),
       (71, 'I appreciate a partner who enjoys cooking or baking, particularly when it comes to...'),
       (72, 'I''m a fan of hiking and exploring nature trails, especially those that lead to...'),
       (73, 'I find inspiration in motivational speakers, particularly those who talk about...'),
       (74, 'I enjoy attending sports events, particularly those that involve...'),
       (75, 'I appreciate someone who has a love for adventure travel, especially when it comes to...'),
       (76, 'I''m a fan of stand-up comedy, particularly comedians who joke about...'),
       (77, 'I find relaxation in activities such as writing or journaling, especially...'),
       (78, 'I enjoy attending book readings or literary events, particularly those featuring...'),
       (79, 'I appreciate a partner who values sustainable living and practices habits like...'),
       (80, 'I''m a fan of documentaries, especially those that delve into...'),
       (81, 'I find joy in attending music concerts, particularly those of...'),
       (82, 'I enjoy exploring art galleries, particularly those that showcase...'),
       (83, 'I appreciate someone who enjoys outdoor activities like camping or hiking, especially when it comes to...'),
       (84, 'I''m a fan of period dramas, particularly those set in...'),
       (85, 'I find inspiration in motivational quotes or affirmations, especially those that...'),
       (86, 'I enjoy attending food festivals, particularly those that highlight...'),
       (87, 'I appreciate a partner who is knowledgeable about science and enjoys discussing topics like...'),
       (88, 'I''m a fan of live performances, particularly those that involve...'),
       (89, 'I find relaxation in activities such as practicing mindfulness or meditation, especially...'),
       (90, 'I enjoy attending fashion shows or runway events, particularly those showcasing...'),
       (91, 'I appreciate someone who has a passion for social activism and supports causes like...'),
       (92, 'I''m a fan of documentaries, especially those that explore...'),
       (93, 'I find joy in attending cultural workshops or classes, particularly those focused on...'),
       (94, 'I enjoy exploring antique shops and vintage markets, especially when looking for...'),
       (95, 'I appreciate a partner who enjoys outdoor water activities like swimming or kayaking, especially when it comes to...'),
       (96, 'I''m a fan of historical dramas, particularly those set in...'),
       (97, 'I find inspiration in motivational podcasts or TED Talks, especially those that discuss...'),
       (98, 'I enjoy attending beer or wine tasting events, particularly those that feature...'),
       (99, 'I appreciate someone who values equality and inclusivity, especially when it comes to...');
