ALTER TABLE interests_details ADD COLUMN `emoticon` VARCHAR(255);

UPDATE interests_details SET `emoticon` = '🧘' where `interest_values` = 'Therapy';
UPDATE interests_details SET `emoticon` = '🧘‍♂' where `interest_values` = 'Mindfulness';
UPDATE interests_details SET `emoticon` = '💬' where `interest_values` = 'Deep chats';
UPDATE interests_details SET `emoticon` = '📵' where `interest_values` = 'Time offline';
UPDATE interests_details SET `emoticon` = '😴' where `interest_values` = 'Sleeping Well';
UPDATE interests_details SET `emoticon` = '🍎' where `interest_values` = 'Nutrition';
UPDATE interests_details SET `emoticon` = '🏃‍♂️' where `interest_values` = 'Running';
UPDATE interests_details SET `emoticon` = '🧘‍♀' where `interest_values` = 'Yoga';
UPDATE interests_details SET `emoticon` = '🧘‍♂' where `interest_values` = 'Pilates';
UPDATE interests_details SET `emoticon` = '🏋️‍♂' where `interest_values` = 'Gym';
UPDATE interests_details SET `emoticon` = '⚽' where `interest_values` = 'Football';
UPDATE interests_details SET `emoticon` = '🏏' where `interest_values` = 'Cricket';
UPDATE interests_details SET `emoticon` = '🎾' where `interest_values` = 'Tennis';
UPDATE interests_details SET `emoticon` = '🏸' where `interest_values` = 'Badminton';
UPDATE interests_details SET `emoticon` = '🎨' where `interest_values` = 'Art';
UPDATE interests_details SET `emoticon` = '🎨' where `interest_values` = 'Design';
UPDATE interests_details SET `emoticon` = '💄' where `interest_values` = 'Make-up';
UPDATE interests_details SET `emoticon` = '📷' where `interest_values` = 'Photography';
UPDATE interests_details SET `emoticon` = '📝' where `interest_values` = 'Writing';
UPDATE interests_details SET `emoticon` = '🎤' where `interest_values` = 'Singing';
UPDATE interests_details SET `emoticon` = '💃🏻🕺🏻' where `interest_values` = 'Dancing';
UPDATE interests_details SET `emoticon` = '🎨' where `interest_values` = 'Crafts';
UPDATE interests_details SET `emoticon` = '📹' where `interest_values` = 'Making Videos';
UPDATE interests_details SET `emoticon` = '💕' where `interest_values` = 'Romance';
UPDATE interests_details SET `emoticon` = '😂' where `interest_values` = 'Comedy';
UPDATE interests_details SET `emoticon` = '🎭' where `interest_values` = 'Drama';
UPDATE interests_details SET `emoticon` = '😱' where `interest_values` = 'Horror';
UPDATE interests_details SET `emoticon` = '🔪' where `interest_values` = 'Thriller';
UPDATE interests_details SET `emoticon` = '🧙🏻‍♀' where `interest_values` = 'Fantasy';
UPDATE interests_details SET `emoticon` = '🚀' where `interest_values` = 'Sci-Fi';
UPDATE interests_details SET `emoticon` = '👧🏻' where `interest_values` = 'Anime';
UPDATE interests_details SET `emoticon` = '🎮' where `interest_values` = 'Video games';
UPDATE interests_details SET `emoticon` = '🎲' where `interest_values` = 'Board games';
UPDATE interests_details SET `emoticon` = '🌻' where `interest_values` = 'Gardening';
UPDATE interests_details SET `emoticon` = '🍳' where `interest_values` = 'Cooking';
UPDATE interests_details SET `emoticon` = '🧁' where `interest_values` = 'Baking';
UPDATE interests_details SET `emoticon` = '🥡' where `interest_values` = 'Takeout';
UPDATE interests_details SET `emoticon` = '💕' where `interest_values` = 'Romance';
UPDATE interests_details SET `emoticon` = '😂' where `interest_values` = 'Comedy';
UPDATE interests_details SET `emoticon` = '🚀' where `interest_values` = 'Sci-Fi';
UPDATE interests_details SET `emoticon` = '👻' where `interest_values` = 'Horror';
UPDATE interests_details SET `emoticon` = '🔪' where `interest_values` = 'Thriller';
UPDATE interests_details SET `emoticon` = '🧙‍♀' where `interest_values` = 'Fantasy';
UPDATE interests_details SET `emoticon` = '🕵️‍♀' where `interest_values` = 'Mystery';
UPDATE interests_details SET `emoticon` = '📚👦' where `interest_values` = 'Manga';
UPDATE interests_details SET `emoticon` = '🎤💃' where `interest_values` = 'Hip Hop';
UPDATE interests_details SET `emoticon` = '🎸🤘' where `interest_values` = 'Rock';
UPDATE interests_details SET `emoticon` = '🎧🎹' where `interest_values` = 'Electronic';
UPDATE interests_details SET `emoticon` = '🎷🎺' where `interest_values` = 'Jazz';
UPDATE interests_details SET `emoticon` = '🍷🍇' where `interest_values` = 'Wine';
UPDATE interests_details SET `emoticon` = '🍺🍻' where `interest_values` = 'Beer';
UPDATE interests_details SET `emoticon` = '☕️☕' where `interest_values` = 'Coffee';
UPDATE interests_details SET `emoticon` = '🍸🍹' where `interest_values` = 'Cocktails';
UPDATE interests_details SET `emoticon` = '🎻🎼' where `interest_values` = 'Classical';
UPDATE interests_details SET `emoticon` = '🥃' where `interest_values` = 'Whisky';
UPDATE interests_details SET `emoticon` = '🌱' where `interest_values` = 'Vegan';
UPDATE interests_details SET `emoticon` = '🍕' where `interest_values` = 'Pizza';
UPDATE interests_details SET `emoticon` = '🥦' where `interest_values` = 'Vegetarian';
UPDATE interests_details SET `emoticon` = '🏖️' where `interest_values` = 'Beaches';
UPDATE interests_details SET `emoticon` = '💆‍♀' where `interest_values` = 'Spa weekends';
UPDATE interests_details SET `emoticon` = '❄' where `interest_values` = 'Winter sports';
UPDATE interests_details SET `emoticon` = '🏕' where `interest_values` = 'Camping';
UPDATE interests_details SET `emoticon` = '🌳' where `interest_values` = 'Country escapes';
UPDATE interests_details SET `emoticon` = '🎒' where `interest_values` = 'Backpacking';
UPDATE interests_details SET `emoticon` = '🌇' where `interest_values` = 'City breaks';
UPDATE interests_details SET `emoticon` = '🚶‍♂️🏞️' where `interest_values` = 'Hiking trips';
UPDATE interests_details SET `emoticon` = '🚗' where `interest_values` = 'Road trips';
UPDATE interests_details SET `emoticon` = '🎣' where `interest_values` = 'Fishing trips';
UPDATE interests_details SET `emoticon` = '🐶' where `interest_values` = 'Dogs';
UPDATE interests_details SET `emoticon` = '🐱' where `interest_values` = 'Cats';
UPDATE interests_details SET `emoticon` = '🐦' where `interest_values` = 'Birds';
UPDATE interests_details SET `emoticon` = '🐟' where `interest_values` = 'Fish';
UPDATE interests_details SET `emoticon` = '🐢' where `interest_values` = 'Turtles';
UPDATE interests_details SET `emoticon` = '💪' where `interest_values` = 'Being active';
UPDATE interests_details SET `emoticon` = '💪🏼' where `interest_values` = 'Ambition';
UPDATE interests_details SET `emoticon` = '🎉' where `interest_values` = 'Confidence';
UPDATE interests_details SET `emoticon` = '🌟' where `interest_values` = 'Positivity';
UPDATE interests_details SET `emoticon` = '🎨' where `interest_values` = 'Creativity';
UPDATE interests_details SET `emoticon` = '👨‍👩‍👧' where `interest_values` = 'Being family oriented';
UPDATE interests_details SET `emoticon` = '🧠' where `interest_values` = 'Intelligence';
UPDATE interests_details SET `emoticon` = '❤' where `interest_values` = 'Empathy';
UPDATE interests_details SET `emoticon` = '🏳️‍🌈' where `interest_values` = 'Trans ally';
UPDATE interests_details SET `emoticon` = '🏳️‍' where `interest_values` = 'LGBTQIA+ ally';
UPDATE interests_details SET `emoticon` = '🤝' where `interest_values` = 'Feminism';
UPDATE interests_details SET `emoticon` = '🗳️💪' where `interest_values` = 'Voter rights';
UPDATE interests_details SET `emoticon` = '👥🌍🙌' where `interest_values` = 'Human rights';
UPDATE interests_details SET `emoticon` = '🌍♻' where `interest_values` = 'Environmentalism';
UPDATE interests_details SET `emoticon` = '🎤🎶' where `interest_values` = 'Gigs';
UPDATE interests_details SET `emoticon` = '🎤💃🤣' where `interest_values` = 'Stand up';
UPDATE interests_details SET `emoticon` = '🎉' where `interest_values` = 'Festivals';
UPDATE interests_details SET `emoticon` = '🏛️' where `interest_values` = 'Museums & galleries';
UPDATE interests_details SET `emoticon` = '🎨' where `interest_values` = 'Theatre';
UPDATE interests_details SET `emoticon` = '🎭🕺' where `interest_values` = 'Nightclubs';
UPDATE interests_details SET `emoticon` = '🍸' where `interest_values` = 'Bars';
UPDATE interests_details SET `emoticon` = '🎤' where `interest_values` = 'Karaoke';
UPDATE interests_details SET `emoticon` = '☕' where `interest_values` = 'Cafe-hopping';
