CREATE TABLE IF NOT EXISTS user_profile (
    ID INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    is_verified boolean default false,
    is_premium boolean default false,
    date_of_birth DATE,
    gender VARCHAR(20),
    sexual_orientation VARCHAR(20),
    latitude FLOAT,
    longitude FLOAT,
    education_level VARCHAR(20),
    college VARCHAR(100),
    occupation VARCHAR(20),
    marital_status VARCHAR(20),
    religion VARCHAR(20),
    height INT,
    weight INT,
    looking_for VARCHAR(20),
    exercise VARCHAR(20),
    drink VARCHAR(20),
    smoke VARCHAR(20),
    about VARCHAR(100),
    deleted_at TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (user_id) REFERENCES users(ID)
);

